language: node_js
node_js:
  - "lts/*"
  - "node"
  - "8"
jobs:
  include:
    - stage: lint
      script: npx eslint .
    - stage: Produce Coverage
      script: npm run build && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
