language: node_js
node_js:
  - "lts/*"
  - "node"
  - "8"
jobs:
  include:
    - stage: test
      script: git diff --name-only master..$TRAVIS_BRANCH | grep -E '\.js$' | xargs npx eslint
      script: npm test
      